using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace Hell_Island_Fell.Encounters
{
    public class CustomGardenEncounters
    {
        public static void Add()
        {
            List<RandomEnemyGroup> herImageEasy = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHerImage_Easy_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "Maneater_EN",
                "InHerImage_EN",
                "InHisImage_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "InHerImage_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "ScatterbrainedNosestone_EN",
                "InHerImage_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "SweatingNosestone_EN",
                "InHerImage_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "InHerImage_EN",
                "InHerImage_EN",
                "Inequity_EN",
            ]),
                new(
            [
                "InHerImage_EN",
                "InHerImage_EN",
                "Inequity_EN",
                "NextOfKin_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                herImageEasy.Add(new(
                    [
                        "InHerImage_EN",
                        "Inequity_EN",
                        "SterileBud_EN",
                    ]));
                herImageEasy.Add(new(
                    [
                        "InHerImage_EN",
                        "UninspiredNosestone_EN",
                        "SterileBud_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                herImageEasy.Add(new(
                    [
                        "InHerImage_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHerImage_Easy_EnemyBundle"))._enemyBundles = herImageEasy;

            List<RandomEnemyGroup> hisImageEasy = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHisImage_Easy_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "Maneater_EN",
                "InHisImage_EN",
                "InHisImage_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "InHerImage_EN",
                "InHisImage_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "InHisImage_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "ProlificNosestone_EN",
                "InHisImage_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "InHisImage_EN",
                "InHerImage_EN",
                "Inequity_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "InHisImage_EN",
                "InHerImage_EN",
                "Inequity_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                hisImageEasy.Add(new(
                    [
                        "InHisImage_EN",
                        "ProlificNosestone_EN",
                        "SterileBud_EN",
                    ]));
                hisImageEasy.Add(new(
                    [
                        "InHisImage_EN",
                        "ProlificNosestone_EN",
                        "Unterling_EN",
                        "Unterling_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                hisImageEasy.Add(new(
                    [
                        "InHisImage_EN",
                        "ProlificNosestone_EN",
                        "EggKeeper_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHisImage_Easy_EnemyBundle"))._enemyBundles = hisImageEasy;

            List<RandomEnemyGroup> gigglingMinisterEasy = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_GigglingMinister_Easy_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "Maneater_EN",
                "GigglingMinister_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "GigglingMinister_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "ScatterbrainedNosestone_EN"
            ]),
                new(
            [
                "GigglingMinister_EN",
                "UninspiredNosestone_EN"
            ]),
                new(
            [
                "Inequity_EN",
                "GigglingMinister_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                gigglingMinisterEasy.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "Unterling_EN",
                    ]));
                gigglingMinisterEasy.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "TitteringPeon_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                gigglingMinisterEasy.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
                gigglingMinisterEasy.Add(new(
                    [
                        "GigglingMinister_EN",
                        "StickingHomunculus_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                gigglingMinisterEasy.Add(new(
                    [
                        "GigglingMinister_EN",
                        "StickingHomunculus_EN",
                        "Vagabond_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_GigglingMinister_Easy_EnemyBundle"))._enemyBundles = gigglingMinisterEasy;

            List<RandomEnemyGroup> choirBoyEasy = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_ChoirBoy_Easy_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "UninspiredNosestone_EN",
                "SweatingNosestone_EN",
                "ChoirBoy_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "ProlificNosestone_EN",
                "ChoirBoy_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "ChoirBoy_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "ChoirBoy_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                choirBoyEasy.Add(new(
                    [
                        "ChoirBoy_EN",
                        "Inequity_EN",
                        "Unterling_EN",
                    ]));
                choirBoyEasy.Add(new(
                    [
                        "ChoirBoy_EN",
                        "Inequity_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                choirBoyEasy.Add(new(
                    [
                        "ChoirBoy_EN",
                        "Inequity_EN",
                        "SterileBud_EN",
                    ]));
                choirBoyEasy.Add(new(
                    [
                        "ChoirBoy_EN",
                        "Inequity_EN",
                        "TitteringPeon_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                choirBoyEasy.Add(new(
                    [
                        "ChoirBoy_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                choirBoyEasy.Add(new(
                    [
                        "ChoirBoy_EN",
                        "Inequity_EN",
                        "FrowningChancellor_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_ChoirBoy_Easy_EnemyBundle"))._enemyBundles = choirBoyEasy;

            List<RandomEnemyGroup> skinningHomunculusMedium = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_SkinningHomunculus_Medium_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "Maneater_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "SkinningHomunculus_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "SkinningHomunculus_EN",
                "NextOfKin_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "ProlificNosestone_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "SkinningHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
                new(
            [
                "SkinningHomunculus_EN",
                "ShiveringHomunculus_EN",
                "StickingHomunculus_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN"
                    ]));
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "Inequity_EN",
                        "ScreamingHomunculus_EN"
                    ]));
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "Maneater_EN",
                        "ScreamingHomunculus_EN"
                    ]));
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ProlificNosestone_EN",
                        "ScreamingHomunculus_EN"
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ProlificNosestone_EN",
                        "EggKeeper_EN"
                    ]));
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "SweatingNosestone_EN",
                        "EggKeeper_EN"
                    ]));
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "Maneater_EN",
                        "EggKeeper_EN"
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "Maneater_EN",
                        "Vagabond_EN"
                    ]));
                skinningHomunculusMedium.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "Maneater_EN",
                        "FrowningChancellor_EN"
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_SkinningHomunculus_Medium_EnemyBundle"))._enemyBundles = skinningHomunculusMedium;

            List<RandomEnemyGroup> shiveringHomunculusMedium = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_ShiveringHomunculus_Medium_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "SweatingNosestone_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
                new(
            [
                "MesmerizingNosestone_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                shiveringHomunculusMedium.Add(new(
                    [
                        "ShiveringHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_ShiveringHomunculus_Medium_EnemyBundle"))._enemyBundles = shiveringHomunculusMedium;

            List<RandomEnemyGroup> hisImageMedium = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHisImage_Medium_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "SweatingNosestone_EN",
                "InHisImage_EN",
                "InHisImage_EN",
                "InHisImage_EN",
            ]),
                new(
            [
                "ProlificNosestone_EN",
                "InHisImage_EN",
                "InHisImage_EN",
                "InHisImage_EN",
            ]),
                new(
            [
                "MesmerizingNosestone_EN",
                "InHisImage_EN",
                "InHisImage_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "InHisImage_EN",
                "InHisImage_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "InHisImage_EN",
                "InHisImage_EN",
                "InHerImage_EN",
            ]),
                new(
            [
                "Maneater_EN",
                "InHisImage_EN",
                "InHisImage_EN",
                "InHerImage_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHisImage_EN",
                        "ProlificNosestone_EN",
                        "SterileBud_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHisImage_EN",
                        "UninspiredNosestone_EN",
                        "Unterling_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHisImage_EN",
                        "Inequity_EN",
                        "TitteringPeon_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "Inequity_EN",
                        "Unterling_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "Maneater_EN",
                        "Unterling_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "Maneater_EN",
                        "SterileBud_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "Maneater_EN",
                        "TitteringPeon_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "SweatingNosestone_EN",
                        "TitteringPeon_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "ScatterbrainedNosestone_EN",
                        "TitteringPeon_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHisImage_EN",
                        "ProlificNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHisImage_EN",
                        "SweatingNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "StickingHomunculus_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "StickingHomunculus_EN",
                        "Vagabond_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "ProlificNosestone_EN",
                        "Vagabond_EN",
                    ]));
                hisImageMedium.Add(new(
                    [
                        "InHisImage_EN",
                        "InHerImage_EN",
                        "Maneater_EN",
                        "Vagabond_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHisImage_Medium_EnemyBundle"))._enemyBundles = hisImageMedium;

            List<RandomEnemyGroup> herImageMedium = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHerImage_Medium_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "ScatterbrainedNosestone_EN",
                "InHerImage_EN",
                "InHerImage_EN",
                "InHerImage_EN",
            ]),
                new(
            [
                "MesmerizingNosestone_EN",
                "InHerImage_EN",
                "InHerImage_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "InHisImage_EN",
                "InHerImage_EN",
                "InHerImage_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "InHisImage_EN",
                "InHerImage_EN",
                "UninspiredNosestone_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "ScatterbrainedNosestone_EN",
                        "Unterling_EN",
                    ]));
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "ScatterbrainedNosestone_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "Maneater_EN",
                        "ScatterbrainedNosestone_EN",
                        "SterileBud_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "ScatterbrainedNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "SweatingNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "ScatterbrainedNosestone_EN",
                        "Vagabond_EN",
                    ]));
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "ScatterbrainedNosestone_EN",
                        "FrowningChancellor_EN",
                    ]));
                herImageMedium.Add(new(
                    [
                        "InHerImage_EN",
                        "InHerImage_EN",
                        "Maneater_EN",
                        "FrowningChancellor_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_InHerImage_Medium_EnemyBundle"))._enemyBundles = herImageMedium;

            List<RandomEnemyGroup> gigglingMinisterMedium = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_GigglingMinister_Medium_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "GigglingMinister_EN",
                "Maneater_EN"
            ]),
                new(
            [
                "GigglingMinister_EN",
                "SweatingNosestone_EN"
            ]),
                new(
            [
                "GigglingMinister_EN",
                "ProlificNosestone_EN",
                "Maneater_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "UninspiredNosestone_EN",
                "Maneater_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "Inequity_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "StickingHomunculus_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "StickingHomunculus_EN",
                "UninspiredNosestone_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                gigglingMinisterMedium.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "Unterling_EN",
                    ]));
                gigglingMinisterMedium.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Maneater_EN",
                        "TitteringPeon_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                gigglingMinisterMedium.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Maneater_EN",
                        "EggKeeper_EN",
                    ]));
                gigglingMinisterMedium.Add(new(
                    [
                        "GigglingMinister_EN",
                        "SweatingNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                gigglingMinisterMedium.Add(new(
                    [
                        "GigglingMinister_EN",
                        "StickingHomunculus_EN",
                        "EggKeeper_EN",
                    ]));
                gigglingMinisterMedium.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                gigglingMinisterMedium.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "Vagabond_EN",
                        "NextOfKin_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_GigglingMinister_Medium_EnemyBundle"))._enemyBundles = gigglingMinisterMedium;

            List<RandomEnemyGroup> skinningHomunculusHard = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_SkinningHomunculus_Hard_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "SweatingNosestone_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "SweatingNosestone_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
                new(
            [
                "ProlificNosestone_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "MesmerizingNosestone_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "SweatingNosestone_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "Inequity_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
                "SweatingNosestone_EN",
            ]),
                new(
            [
                "Inequity_EN",
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
                "Maneater_EN",
            ]),
                new(
            [
                "SkinningHomunculus_EN",
                "SkinningHomunculus_EN",
                "ShiveringHomunculus_EN",
                "StickingHomunculus_EN",
            ]),
                new(
            [
                "SkinningHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
                "StickingHomunculus_EN",
            ]),
                new(
            [
                "SkinningHomunculus_EN",
                "StickingHomunculus_EN",
                "Maneater_EN",
            ]),
                new(
            [
                "SkinningHomunculus_EN",
                "StickingHomunculus_EN",
                "Inequity_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                        "ProlificNosestone_EN"
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                        "Maneater_EN"
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                        "ImpenetrableAngler_EN"
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ProlificNosestone_EN",
                        "Unterling_EN",
                        "Unterling_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ScatterbrainedNosestone_EN",
                        "Unterling_EN",
                        "Unterling_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "MesmerizingNosestone_EN",
                        "TitteringPeon_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "MesmerizingNosestone_EN",
                        "SterileBud_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "ProlificNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "SweatingNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "ProlificNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EnemyPack && Hell_Island_Fell.CrossMod.EggKeeper)
            {
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ScreamingHomunculus_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ScreamingHomunculus_EN",
                        "ProlificNosestone_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "StickingHomunculus_EN",
                        "Vagabond_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "ProlificNosestone_EN",
                        "MarbleMaw_EN",
                    ]));
                skinningHomunculusHard.Add(new(
                    [
                        "SkinningHomunculus_EN",
                        "SkinningHomunculus_EN",
                        "Inequity_EN",
                        "FrowningChancellor_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_SkinningHomunculus_Hard_EnemyBundle"))._enemyBundles = skinningHomunculusHard;

            List<RandomEnemyGroup> gigglingMinisterHard = new List<RandomEnemyGroup>(((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_GigglingMinister_Hard_EnemyBundle"))._enemyBundles)
            {
                new(
            [
                "SweatingNosestone_EN",
                "GigglingMinister_EN",
                "GigglingMinister_EN",
            ]),
                new(
            [
                "MesmerizingNosestone_EN",
                "UninspiredNosestone_EN",
                "GigglingMinister_EN",
                "GigglingMinister_EN",
            ]),
                new(
            [
                "ScatterbrainedNosestone_EN",
                "GigglingMinister_EN",
                "GigglingMinister_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "SweatingNosestone_EN",
                "Maneater_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "MesmerizingNosestone_EN",
                "Maneater_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "Inequity_EN",
                "NextOfKin_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "GigglingMinister_EN",
                "Inequity_EN",
                "ChoirBoy_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "Inequity_EN",
                "SweatingNosestone_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "Inequity_EN",
                "MesmerizingNosestone_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "Inequity_EN",
                "SkinningHomunculus_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "GigglingMinister_EN",
                "StickingHomunculus_EN",
                "StickingHomunculus_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "StickingHomunculus_EN",
                "SkinningHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "StickingHomunculus_EN",
                "ShiveringHomunculus_EN",
                "ShiveringHomunculus_EN",
            ]),
                new(
            [
                "GigglingMinister_EN",
                "GigglingMinister_EN",
                "Maneater_EN",
            ]),
            };
            if (Hell_Island_Fell.CrossMod.EnemyPack)
            {
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "StickingHomunculus_EN",
                        "ShiveringHomunculus_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "MesmerizingNosestone_EN",
                        "ScreamingHomunculus_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "SweatingNosestone_EN",
                        "ImpenetrableAngler_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "GigglingMinister_EN",
                        "Maneater_EN",
                        "SterileBud_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "GigglingMinister_EN",
                        "Maneater_EN",
                        "Unterling_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "Unterling_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "UninspiredNosestone_EN",
                        "Unterling_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "GigglingMinister_EN",
                        "UninspiredNosestone_EN",
                        "Unterling_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.EggKeeper)
            {
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "MesmerizingNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "GigglingMinister_EN",
                        "ScatterbrainedNosestone_EN",
                        "EggKeeper_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "EggKeeper_EN",
                    ]));
            }
            if (Hell_Island_Fell.CrossMod.GlitchFreaks)
            {
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "FrowningChancellor_EN",
                    ]));
                gigglingMinisterHard.Add(new(
                    [
                        "GigglingMinister_EN",
                        "Inequity_EN",
                        "Vagabond_EN",
                    ]));
            }
            ((RandomEnemyBundleSO)LoadedAssetsHandler.GetEnemyBundle("H_Zone03_GigglingMinister_Hard_EnemyBundle"))._enemyBundles = gigglingMinisterHard;
        }
    }
}
